# Generated by Django 5.2.1 on 2025-05-15 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hall",
            name="limit",
            field=models.PositiveSmallIntegerField(default=10, verbose_name="лимит стеллажей"),
        ),
        migrations.AddField(
            model_name="library",
            name="limit",
            field=models.PositiveSmallIntegerField(default=10, verbose_name="лимит залов"),
        ),
        migrations.AddField(
            model_name="rack",
            name="limit",
            field=models.PositiveSmallIntegerField(default=10, verbose_name="лимит полок"),
        ),
        migrations.AddField(
            model_name="shelf",
            name="limit",
            field=models.PositiveSmallIntegerField(default=10, verbose_name="лимит книг"),
        ),
    ]
